
import {
  Flame,
  Shield,
  User,
  Skull,
  Building,
  Home,
  Building2,
  Factory,
  Landmark,
  Play,
  Pause,
  FastForward,
  Wind,
  Plus,
  MousePointer,
  Siren,
  ShieldCheck,
  AlertOctagon,
  RotateCw,
  Square,
  X,
  CheckCircle,
  BrainCircuit,
  HandCoins,
  Megaphone,
  SprayCan,
  Car,
  ToyBrick,
  type LucideProps,
} from 'lucide-react';

export const Icons = {
  fire: Flame,
  police: Shield,
  civilian: User,
  arsonist: Skull,
  fireStation: Building,
  policeStation: Siren,
  residential: Home,
  commercial: Building2,
  industrial: Factory,
  public: Landmark,
  play: Play,
  pause: Pause,
  speed: FastForward,
  wind: Wind,
  add: Plus,
  cursor: MousePointer,
  apprehended: ShieldCheck,
  trapped: AlertOctagon,
  reset: RotateCw,
  end: Square,
  burntOut: X,
  extinguished: CheckCircle,
  traffic: Car,
  KINDERGARTEN: ToyBrick,
  // Arsonist Profile Icons
  PYROMANIAC: BrainCircuit,
  GRIFTER: HandCoins,
  PROTESTER: Megaphone,
  VANDAL: SprayCan,
};
